// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type CreateRunbookExecutionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Attaches a runbook to an incident and executes it
	RunbooksExecutionEntity *components.RunbooksExecutionEntity
}

func (o *CreateRunbookExecutionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateRunbookExecutionResponse) GetRunbooksExecutionEntity() *components.RunbooksExecutionEntity {
	if o == nil {
		return nil
	}
	return o.RunbooksExecutionEntity
}
