// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type CreateRetrospectiveReportResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Create a report
	PostMortemsPostMortemReportEntity *components.PostMortemsPostMortemReportEntity
}

func (o *CreateRetrospectiveReportResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateRetrospectiveReportResponse) GetPostMortemsPostMortemReportEntity() *components.PostMortemsPostMortemReportEntity {
	if o == nil {
		return nil
	}
	return o.PostMortemsPostMortemReportEntity
}
