// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type CreateStatusPageSubscriptionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Subscribe to status page updates
	NuncNuncSubscription *components.NuncNuncSubscription
}

func (o *CreateStatusPageSubscriptionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateStatusPageSubscriptionResponse) GetNuncNuncSubscription() *components.NuncNuncSubscription {
	if o == nil {
		return nil
	}
	return o.NuncNuncSubscription
}
