// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type DeleteV1TeamsTeamIDEscalationPoliciesIDRequest struct {
	TeamID string `pathParam:"style=simple,explode=false,name=team_id"`
	ID     string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteV1TeamsTeamIDEscalationPoliciesIDRequest) GetTeamID() string {
	if o == nil {
		return ""
	}
	return o.TeamID
}

func (o *DeleteV1TeamsTeamIDEscalationPoliciesIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type DeleteV1TeamsTeamIDEscalationPoliciesIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteV1TeamsTeamIDEscalationPoliciesIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
