// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type DeleteV1SeverityMatrixConditionsConditionIDRequest struct {
	ConditionID string `pathParam:"style=simple,explode=false,name=condition_id"`
}

func (o *DeleteV1SeverityMatrixConditionsConditionIDRequest) GetConditionID() string {
	if o == nil {
		return ""
	}
	return o.ConditionID
}

type DeleteV1SeverityMatrixConditionsConditionIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Delete a specific condition
	SeverityMatrixConditionEntity *components.SeverityMatrixConditionEntity
}

func (o *DeleteV1SeverityMatrixConditionsConditionIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteV1SeverityMatrixConditionsConditionIDResponse) GetSeverityMatrixConditionEntity() *components.SeverityMatrixConditionEntity {
	if o == nil {
		return nil
	}
	return o.SeverityMatrixConditionEntity
}
