// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type DeleteCustomFieldDefinitionRequest struct {
	FieldID string `pathParam:"style=simple,explode=false,name=field_id"`
}

func (o *DeleteCustomFieldDefinitionRequest) GetFieldID() string {
	if o == nil {
		return ""
	}
	return o.FieldID
}

type DeleteCustomFieldDefinitionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Delete a custom field definition
	OrganizationsCustomFieldDefinitionEntity *components.OrganizationsCustomFieldDefinitionEntity
}

func (o *DeleteCustomFieldDefinitionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteCustomFieldDefinitionResponse) GetOrganizationsCustomFieldDefinitionEntity() *components.OrganizationsCustomFieldDefinitionEntity {
	if o == nil {
		return nil
	}
	return o.OrganizationsCustomFieldDefinitionEntity
}
