// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type DeleteV1TicketingTicketsTicketIDRequest struct {
	TicketID string `pathParam:"style=simple,explode=false,name=ticket_id"`
}

func (o *DeleteV1TicketingTicketsTicketIDRequest) GetTicketID() string {
	if o == nil {
		return ""
	}
	return o.TicketID
}

type DeleteV1TicketingTicketsTicketIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteV1TicketingTicketsTicketIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
