// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type DeleteIncidentLinkRequest struct {
	LinkID     string `pathParam:"style=simple,explode=false,name=link_id"`
	IncidentID string `pathParam:"style=simple,explode=false,name=incident_id"`
}

func (o *DeleteIncidentLinkRequest) GetLinkID() string {
	if o == nil {
		return ""
	}
	return o.LinkID
}

func (o *DeleteIncidentLinkRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

type DeleteIncidentLinkResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteIncidentLinkResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
