// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type GetAwsCloudtrailBatchEventsRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetAwsCloudtrailBatchEventsRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetAwsCloudtrailBatchEventsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *GetAwsCloudtrailBatchEventsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
