// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type GetRunbookExecutionRequest struct {
	ExecutionID string `pathParam:"style=simple,explode=false,name=execution_id"`
}

func (o *GetRunbookExecutionRequest) GetExecutionID() string {
	if o == nil {
		return ""
	}
	return o.ExecutionID
}

type GetRunbookExecutionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Retrieve a runbook execution by ID
	RunbooksExecutionEntity *components.RunbooksExecutionEntity
}

func (o *GetRunbookExecutionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetRunbookExecutionResponse) GetRunbooksExecutionEntity() *components.RunbooksExecutionEntity {
	if o == nil {
		return nil
	}
	return o.RunbooksExecutionEntity
}
