// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type GetV1TicketingTicketTagsRequest struct {
	Prefix *string `queryParam:"style=form,explode=true,name=prefix"`
}

func (o *GetV1TicketingTicketTagsRequest) GetPrefix() *string {
	if o == nil {
		return nil
	}
	return o.Prefix
}

type GetV1TicketingTicketTagsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List all of the ticket tags in the organization
	TagEntityPaginated *components.TagEntityPaginated
}

func (o *GetV1TicketingTicketTagsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetV1TicketingTicketTagsResponse) GetTagEntityPaginated() *components.TagEntityPaginated {
	if o == nil {
		return nil
	}
	return o.TagEntityPaginated
}
