// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type GetV1IncidentsIncidentIDAlertsRequest struct {
	IncidentID string `pathParam:"style=simple,explode=false,name=incident_id"`
}

func (o *GetV1IncidentsIncidentIDAlertsRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

type GetV1IncidentsIncidentIDAlertsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List alerts that have been attached to an incident
	IncidentsAlertEntityPaginated *components.IncidentsAlertEntityPaginated
}

func (o *GetV1IncidentsIncidentIDAlertsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetV1IncidentsIncidentIDAlertsResponse) GetIncidentsAlertEntityPaginated() *components.IncidentsAlertEntityPaginated {
	if o == nil {
		return nil
	}
	return o.IncidentsAlertEntityPaginated
}
