// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type GetV1FunctionalitiesFunctionalityIDServicesRequest struct {
	FunctionalityID string `pathParam:"style=simple,explode=false,name=functionality_id"`
}

func (o *GetV1FunctionalitiesFunctionalityIDServicesRequest) GetFunctionalityID() string {
	if o == nil {
		return ""
	}
	return o.FunctionalityID
}

type GetV1FunctionalitiesFunctionalityIDServicesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *GetV1FunctionalitiesFunctionalityIDServicesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
