// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type GetV1IncidentsIncidentIDAttachmentsRequest struct {
	IncidentID     string  `pathParam:"style=simple,explode=false,name=incident_id"`
	AttachableType *string `queryParam:"style=form,explode=true,name=attachable_type"`
	Page           *int    `queryParam:"style=form,explode=true,name=page"`
	PerPage        *int    `queryParam:"style=form,explode=true,name=per_page"`
}

func (o *GetV1IncidentsIncidentIDAttachmentsRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

func (o *GetV1IncidentsIncidentIDAttachmentsRequest) GetAttachableType() *string {
	if o == nil {
		return nil
	}
	return o.AttachableType
}

func (o *GetV1IncidentsIncidentIDAttachmentsRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *GetV1IncidentsIncidentIDAttachmentsRequest) GetPerPage() *int {
	if o == nil {
		return nil
	}
	return o.PerPage
}

type GetV1IncidentsIncidentIDAttachmentsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *GetV1IncidentsIncidentIDAttachmentsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
