// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"firehydrant/internal/utils"
	"firehydrant/models/components"
	"fmt"
)

// AuditableType - A query to filter audits by type
type AuditableType string

const (
	AuditableTypeRunbooksStep    AuditableType = "Runbooks::Step"
	AuditableTypeRunbooksRunbook AuditableType = "Runbooks::Runbook"
)

func (e AuditableType) ToPointer() *AuditableType {
	return &e
}
func (e *AuditableType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Runbooks::Step":
		fallthrough
	case "Runbooks::Runbook":
		*e = AuditableType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AuditableType: %v", v)
	}
}

type GetV1RunbookAuditsRequest struct {
	Page    *int `queryParam:"style=form,explode=true,name=page"`
	PerPage *int `queryParam:"style=form,explode=true,name=per_page"`
	// A query to filter audits by type
	AuditableType *AuditableType `default:"Runbooks::Step" queryParam:"style=form,explode=true,name=auditable_type"`
	// A query to sort audits by their created_at timestamp. Options are 'asc' or 'desc'
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
}

func (g GetV1RunbookAuditsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetV1RunbookAuditsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetV1RunbookAuditsRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *GetV1RunbookAuditsRequest) GetPerPage() *int {
	if o == nil {
		return nil
	}
	return o.PerPage
}

func (o *GetV1RunbookAuditsRequest) GetAuditableType() *AuditableType {
	if o == nil {
		return nil
	}
	return o.AuditableType
}

func (o *GetV1RunbookAuditsRequest) GetSort() *string {
	if o == nil {
		return nil
	}
	return o.Sort
}

type GetV1RunbookAuditsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *GetV1RunbookAuditsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
