// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"firehydrant/models/components"
	"fmt"
)

type GetV1IncidentsIncidentIDImpactTypePathParamType string

const (
	GetV1IncidentsIncidentIDImpactTypePathParamTypeEnvironments    GetV1IncidentsIncidentIDImpactTypePathParamType = "environments"
	GetV1IncidentsIncidentIDImpactTypePathParamTypeFunctionalities GetV1IncidentsIncidentIDImpactTypePathParamType = "functionalities"
	GetV1IncidentsIncidentIDImpactTypePathParamTypeServices        GetV1IncidentsIncidentIDImpactTypePathParamType = "services"
	GetV1IncidentsIncidentIDImpactTypePathParamTypeCustomers       GetV1IncidentsIncidentIDImpactTypePathParamType = "customers"
)

func (e GetV1IncidentsIncidentIDImpactTypePathParamType) ToPointer() *GetV1IncidentsIncidentIDImpactTypePathParamType {
	return &e
}
func (e *GetV1IncidentsIncidentIDImpactTypePathParamType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "environments":
		fallthrough
	case "functionalities":
		fallthrough
	case "services":
		fallthrough
	case "customers":
		*e = GetV1IncidentsIncidentIDImpactTypePathParamType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetV1IncidentsIncidentIDImpactTypePathParamType: %v", v)
	}
}

type GetV1IncidentsIncidentIDImpactTypeRequest struct {
	IncidentID string                                          `pathParam:"style=simple,explode=false,name=incident_id"`
	Type       GetV1IncidentsIncidentIDImpactTypePathParamType `pathParam:"style=simple,explode=false,name=type"`
}

func (o *GetV1IncidentsIncidentIDImpactTypeRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

func (o *GetV1IncidentsIncidentIDImpactTypeRequest) GetType() GetV1IncidentsIncidentIDImpactTypePathParamType {
	if o == nil {
		return GetV1IncidentsIncidentIDImpactTypePathParamType("")
	}
	return o.Type
}

type GetV1IncidentsIncidentIDImpactTypeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List impacted infrastructure on an incident by specifying type
	IncidentImpactEntityPaginated *components.IncidentImpactEntityPaginated
}

func (o *GetV1IncidentsIncidentIDImpactTypeResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetV1IncidentsIncidentIDImpactTypeResponse) GetIncidentImpactEntityPaginated() *components.IncidentImpactEntityPaginated {
	if o == nil {
		return nil
	}
	return o.IncidentImpactEntityPaginated
}
