// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type GetV1TicketingProjectsTicketingProjectIDConfigurationOptionsOptionsForFieldIDRequest struct {
	FieldID            string `pathParam:"style=simple,explode=false,name=field_id"`
	TicketingProjectID string `pathParam:"style=simple,explode=false,name=ticketing_project_id"`
}

func (o *GetV1TicketingProjectsTicketingProjectIDConfigurationOptionsOptionsForFieldIDRequest) GetFieldID() string {
	if o == nil {
		return ""
	}
	return o.FieldID
}

func (o *GetV1TicketingProjectsTicketingProjectIDConfigurationOptionsOptionsForFieldIDRequest) GetTicketingProjectID() string {
	if o == nil {
		return ""
	}
	return o.TicketingProjectID
}

type GetV1TicketingProjectsTicketingProjectIDConfigurationOptionsOptionsForFieldIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *GetV1TicketingProjectsTicketingProjectIDConfigurationOptionsOptionsForFieldIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
