// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type ListChecklistTemplatesRequest struct {
	Page    *int `queryParam:"style=form,explode=true,name=page"`
	PerPage *int `queryParam:"style=form,explode=true,name=per_page"`
	// A query to search checklist templates by their name
	Query *string `queryParam:"style=form,explode=true,name=query"`
}

func (o *ListChecklistTemplatesRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListChecklistTemplatesRequest) GetPerPage() *int {
	if o == nil {
		return nil
	}
	return o.PerPage
}

func (o *ListChecklistTemplatesRequest) GetQuery() *string {
	if o == nil {
		return nil
	}
	return o.Query
}

type ListChecklistTemplatesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List all of the checklist templates that have been added to the organization
	ChecklistTemplateEntityPaginated *components.ChecklistTemplateEntityPaginated
}

func (o *ListChecklistTemplatesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListChecklistTemplatesResponse) GetChecklistTemplateEntityPaginated() *components.ChecklistTemplateEntityPaginated {
	if o == nil {
		return nil
	}
	return o.ChecklistTemplateEntityPaginated
}
