// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type ListRetrospectiveQuestionsRequest struct {
	Page    *int `queryParam:"style=form,explode=true,name=page"`
	PerPage *int `queryParam:"style=form,explode=true,name=per_page"`
}

func (o *ListRetrospectiveQuestionsRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListRetrospectiveQuestionsRequest) GetPerPage() *int {
	if o == nil {
		return nil
	}
	return o.PerPage
}

type ListRetrospectiveQuestionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List the questions configured to be provided and filled out on each retrospective report.
	PostMortemsQuestionTypeEntityPaginated *components.PostMortemsQuestionTypeEntityPaginated
}

func (o *ListRetrospectiveQuestionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListRetrospectiveQuestionsResponse) GetPostMortemsQuestionTypeEntityPaginated() *components.PostMortemsQuestionTypeEntityPaginated {
	if o == nil {
		return nil
	}
	return o.PostMortemsQuestionTypeEntityPaginated
}
