// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type ListTicketingProjectsRequest struct {
	SupportsTicketTypes *string `queryParam:"style=form,explode=true,name=supports_ticket_types"`
	Providers           *string `queryParam:"style=form,explode=true,name=providers"`
	ConnectionIds       *string `queryParam:"style=form,explode=true,name=connection_ids"`
	ConfiguredProjects  *bool   `queryParam:"style=form,explode=true,name=configured_projects"`
	Query               *string `queryParam:"style=form,explode=true,name=query"`
	Page                *int    `queryParam:"style=form,explode=true,name=page"`
	PerPage             *int    `queryParam:"style=form,explode=true,name=per_page"`
}

func (o *ListTicketingProjectsRequest) GetSupportsTicketTypes() *string {
	if o == nil {
		return nil
	}
	return o.SupportsTicketTypes
}

func (o *ListTicketingProjectsRequest) GetProviders() *string {
	if o == nil {
		return nil
	}
	return o.Providers
}

func (o *ListTicketingProjectsRequest) GetConnectionIds() *string {
	if o == nil {
		return nil
	}
	return o.ConnectionIds
}

func (o *ListTicketingProjectsRequest) GetConfiguredProjects() *bool {
	if o == nil {
		return nil
	}
	return o.ConfiguredProjects
}

func (o *ListTicketingProjectsRequest) GetQuery() *string {
	if o == nil {
		return nil
	}
	return o.Query
}

func (o *ListTicketingProjectsRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListTicketingProjectsRequest) GetPerPage() *int {
	if o == nil {
		return nil
	}
	return o.PerPage
}

type ListTicketingProjectsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List all ticketing projects available to the organization
	TicketingProjectsProjectListItemEntity *components.TicketingProjectsProjectListItemEntity
}

func (o *ListTicketingProjectsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListTicketingProjectsResponse) GetTicketingProjectsProjectListItemEntity() *components.TicketingProjectsProjectListItemEntity {
	if o == nil {
		return nil
	}
	return o.TicketingProjectsProjectListItemEntity
}
