// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type ListIncidentMilestonesRequest struct {
	IncidentID string `pathParam:"style=simple,explode=false,name=incident_id"`
}

func (o *ListIncidentMilestonesRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

type ListIncidentMilestonesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List times and durations for each milestone on an incident
	IncidentsMilestoneEntityPaginated *components.IncidentsMilestoneEntityPaginated
}

func (o *ListIncidentMilestonesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListIncidentMilestonesResponse) GetIncidentsMilestoneEntityPaginated() *components.IncidentsMilestoneEntityPaginated {
	if o == nil {
		return nil
	}
	return o.IncidentsMilestoneEntityPaginated
}
