// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type ListSignalEmailTargetsRequest struct {
	// A query string to search the list of targets by.
	Query *string `queryParam:"style=form,explode=true,name=query"`
}

func (o *ListSignalEmailTargetsRequest) GetQuery() *string {
	if o == nil {
		return nil
	}
	return o.Query
}

type ListSignalEmailTargetsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *ListSignalEmailTargetsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
