// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type ListSchedulesRequest struct {
	// Filter schedules with a query on their name
	Query   *string `queryParam:"style=form,explode=true,name=query"`
	Page    *int    `queryParam:"style=form,explode=true,name=page"`
	PerPage *int    `queryParam:"style=form,explode=true,name=per_page"`
}

func (o *ListSchedulesRequest) GetQuery() *string {
	if o == nil {
		return nil
	}
	return o.Query
}

func (o *ListSchedulesRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListSchedulesRequest) GetPerPage() *int {
	if o == nil {
		return nil
	}
	return o.PerPage
}

type ListSchedulesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List all known schedules in FireHydrant as pulled from external sources
	ScheduleEntityPaginated *components.ScheduleEntityPaginated
}

func (o *ListSchedulesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListSchedulesResponse) GetScheduleEntityPaginated() *components.ScheduleEntityPaginated {
	if o == nil {
		return nil
	}
	return o.ScheduleEntityPaginated
}
