// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type ListRetrospectiveReportReasonsRequest struct {
	ReportID string `pathParam:"style=simple,explode=false,name=report_id"`
	Page     *int   `queryParam:"style=form,explode=true,name=page"`
	PerPage  *int   `queryParam:"style=form,explode=true,name=per_page"`
}

func (o *ListRetrospectiveReportReasonsRequest) GetReportID() string {
	if o == nil {
		return ""
	}
	return o.ReportID
}

func (o *ListRetrospectiveReportReasonsRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListRetrospectiveReportReasonsRequest) GetPerPage() *int {
	if o == nil {
		return nil
	}
	return o.PerPage
}

type ListRetrospectiveReportReasonsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List all contributing factors to an incident
	PostMortemsReasonEntityPaginated *components.PostMortemsReasonEntityPaginated
}

func (o *ListRetrospectiveReportReasonsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListRetrospectiveReportReasonsResponse) GetPostMortemsReasonEntityPaginated() *components.PostMortemsReasonEntityPaginated {
	if o == nil {
		return nil
	}
	return o.PostMortemsReasonEntityPaginated
}
