// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type PatchV1IntegrationsSlackConnectionsConnectionIDEmojiActionsEmojiActionIDRequestBody struct {
	// The name of the emoji to associate with this action
	EmojiName *string `form:"name=emoji_name"`
	// The ID of the incident type to associate with this emoji action
	IncidentTypeID *string `form:"name=incident_type_id"`
}

func (o *PatchV1IntegrationsSlackConnectionsConnectionIDEmojiActionsEmojiActionIDRequestBody) GetEmojiName() *string {
	if o == nil {
		return nil
	}
	return o.EmojiName
}

func (o *PatchV1IntegrationsSlackConnectionsConnectionIDEmojiActionsEmojiActionIDRequestBody) GetIncidentTypeID() *string {
	if o == nil {
		return nil
	}
	return o.IncidentTypeID
}

type PatchV1IntegrationsSlackConnectionsConnectionIDEmojiActionsEmojiActionIDRequest struct {
	// Slack Connection UUID
	ConnectionID  string                                                                               `pathParam:"style=simple,explode=false,name=connection_id"`
	EmojiActionID string                                                                               `pathParam:"style=simple,explode=false,name=emoji_action_id"`
	RequestBody   *PatchV1IntegrationsSlackConnectionsConnectionIDEmojiActionsEmojiActionIDRequestBody `request:"mediaType=application/x-www-form-urlencoded"`
}

func (o *PatchV1IntegrationsSlackConnectionsConnectionIDEmojiActionsEmojiActionIDRequest) GetConnectionID() string {
	if o == nil {
		return ""
	}
	return o.ConnectionID
}

func (o *PatchV1IntegrationsSlackConnectionsConnectionIDEmojiActionsEmojiActionIDRequest) GetEmojiActionID() string {
	if o == nil {
		return ""
	}
	return o.EmojiActionID
}

func (o *PatchV1IntegrationsSlackConnectionsConnectionIDEmojiActionsEmojiActionIDRequest) GetRequestBody() *PatchV1IntegrationsSlackConnectionsConnectionIDEmojiActionsEmojiActionIDRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type PatchV1IntegrationsSlackConnectionsConnectionIDEmojiActionsEmojiActionIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *PatchV1IntegrationsSlackConnectionsConnectionIDEmojiActionsEmojiActionIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
