// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type PatchV1ScheduledMaintenancesScheduledMaintenanceIDRequest struct {
	ScheduledMaintenanceID                             string                                                        `pathParam:"style=simple,explode=false,name=scheduled_maintenance_id"`
	PatchV1ScheduledMaintenancesScheduledMaintenanceID components.PatchV1ScheduledMaintenancesScheduledMaintenanceID `request:"mediaType=application/json"`
}

func (o *PatchV1ScheduledMaintenancesScheduledMaintenanceIDRequest) GetScheduledMaintenanceID() string {
	if o == nil {
		return ""
	}
	return o.ScheduledMaintenanceID
}

func (o *PatchV1ScheduledMaintenancesScheduledMaintenanceIDRequest) GetPatchV1ScheduledMaintenancesScheduledMaintenanceID() components.PatchV1ScheduledMaintenancesScheduledMaintenanceID {
	if o == nil {
		return components.PatchV1ScheduledMaintenancesScheduledMaintenanceID{}
	}
	return o.PatchV1ScheduledMaintenancesScheduledMaintenanceID
}

type PatchV1ScheduledMaintenancesScheduledMaintenanceIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Change the conditions of a scheduled maintenance event, including updating any status page announcements of changes.
	ScheduledMaintenanceEntity *components.ScheduledMaintenanceEntity
}

func (o *PatchV1ScheduledMaintenancesScheduledMaintenanceIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PatchV1ScheduledMaintenancesScheduledMaintenanceIDResponse) GetScheduledMaintenanceEntity() *components.ScheduledMaintenanceEntity {
	if o == nil {
		return nil
	}
	return o.ScheduledMaintenanceEntity
}
