// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type PatchV1TeamsTeamIDOnCallSchedulesScheduleIDRequest struct {
	TeamID                                      string                                                 `pathParam:"style=simple,explode=false,name=team_id"`
	ScheduleID                                  string                                                 `pathParam:"style=simple,explode=false,name=schedule_id"`
	PatchV1TeamsTeamIDOnCallSchedulesScheduleID components.PatchV1TeamsTeamIDOnCallSchedulesScheduleID `request:"mediaType=application/json"`
}

func (o *PatchV1TeamsTeamIDOnCallSchedulesScheduleIDRequest) GetTeamID() string {
	if o == nil {
		return ""
	}
	return o.TeamID
}

func (o *PatchV1TeamsTeamIDOnCallSchedulesScheduleIDRequest) GetScheduleID() string {
	if o == nil {
		return ""
	}
	return o.ScheduleID
}

func (o *PatchV1TeamsTeamIDOnCallSchedulesScheduleIDRequest) GetPatchV1TeamsTeamIDOnCallSchedulesScheduleID() components.PatchV1TeamsTeamIDOnCallSchedulesScheduleID {
	if o == nil {
		return components.PatchV1TeamsTeamIDOnCallSchedulesScheduleID{}
	}
	return o.PatchV1TeamsTeamIDOnCallSchedulesScheduleID
}

type PatchV1TeamsTeamIDOnCallSchedulesScheduleIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *PatchV1TeamsTeamIDOnCallSchedulesScheduleIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
