// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type PatchV1IncidentsIncidentIDTasksTaskIDRequest struct {
	TaskID                                string                                           `pathParam:"style=simple,explode=false,name=task_id"`
	IncidentID                            string                                           `pathParam:"style=simple,explode=false,name=incident_id"`
	PatchV1IncidentsIncidentIDTasksTaskID components.PatchV1IncidentsIncidentIDTasksTaskID `request:"mediaType=application/json"`
}

func (o *PatchV1IncidentsIncidentIDTasksTaskIDRequest) GetTaskID() string {
	if o == nil {
		return ""
	}
	return o.TaskID
}

func (o *PatchV1IncidentsIncidentIDTasksTaskIDRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

func (o *PatchV1IncidentsIncidentIDTasksTaskIDRequest) GetPatchV1IncidentsIncidentIDTasksTaskID() components.PatchV1IncidentsIncidentIDTasksTaskID {
	if o == nil {
		return components.PatchV1IncidentsIncidentIDTasksTaskID{}
	}
	return o.PatchV1IncidentsIncidentIDTasksTaskID
}

type PatchV1IncidentsIncidentIDTasksTaskIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Update a task's attributes
	TaskEntity *components.TaskEntity
}

func (o *PatchV1IncidentsIncidentIDTasksTaskIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PatchV1IncidentsIncidentIDTasksTaskIDResponse) GetTaskEntity() *components.TaskEntity {
	if o == nil {
		return nil
	}
	return o.TaskEntity
}
