// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type PatchV1PrioritiesPrioritySlugRequest struct {
	PrioritySlug                  string                                   `pathParam:"style=simple,explode=false,name=priority_slug"`
	PatchV1PrioritiesPrioritySlug components.PatchV1PrioritiesPrioritySlug `request:"mediaType=application/json"`
}

func (o *PatchV1PrioritiesPrioritySlugRequest) GetPrioritySlug() string {
	if o == nil {
		return ""
	}
	return o.PrioritySlug
}

func (o *PatchV1PrioritiesPrioritySlugRequest) GetPatchV1PrioritiesPrioritySlug() components.PatchV1PrioritiesPrioritySlug {
	if o == nil {
		return components.PatchV1PrioritiesPrioritySlug{}
	}
	return o.PatchV1PrioritiesPrioritySlug
}

type PatchV1PrioritiesPrioritySlugResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Update a specific priority
	PriorityEntity *components.PriorityEntity
}

func (o *PatchV1PrioritiesPrioritySlugResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PatchV1PrioritiesPrioritySlugResponse) GetPriorityEntity() *components.PriorityEntity {
	if o == nil {
		return nil
	}
	return o.PriorityEntity
}
