// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type PostV1ConversationsConversationIDCommentsRequest struct {
	ConversationID                            string                                               `pathParam:"style=simple,explode=false,name=conversation_id"`
	PostV1ConversationsConversationIDComments components.PostV1ConversationsConversationIDComments `request:"mediaType=application/json"`
}

func (o *PostV1ConversationsConversationIDCommentsRequest) GetConversationID() string {
	if o == nil {
		return ""
	}
	return o.ConversationID
}

func (o *PostV1ConversationsConversationIDCommentsRequest) GetPostV1ConversationsConversationIDComments() components.PostV1ConversationsConversationIDComments {
	if o == nil {
		return components.PostV1ConversationsConversationIDComments{}
	}
	return o.PostV1ConversationsConversationIDComments
}

type PostV1ConversationsConversationIDCommentsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *PostV1ConversationsConversationIDCommentsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
