// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type PostV1SignalsDebuggerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *PostV1SignalsDebuggerResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
