// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type PostV1IncidentsIncidentIDStatusPagesRequest struct {
	IncidentID                           string                                          `pathParam:"style=simple,explode=false,name=incident_id"`
	PostV1IncidentsIncidentIDStatusPages components.PostV1IncidentsIncidentIDStatusPages `request:"mediaType=application/json"`
}

func (o *PostV1IncidentsIncidentIDStatusPagesRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

func (o *PostV1IncidentsIncidentIDStatusPagesRequest) GetPostV1IncidentsIncidentIDStatusPages() components.PostV1IncidentsIncidentIDStatusPages {
	if o == nil {
		return components.PostV1IncidentsIncidentIDStatusPages{}
	}
	return o.PostV1IncidentsIncidentIDStatusPages
}

type PostV1IncidentsIncidentIDStatusPagesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Add a status page to an incident.
	IncidentsStatusPageEntity *components.IncidentsStatusPageEntity
}

func (o *PostV1IncidentsIncidentIDStatusPagesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostV1IncidentsIncidentIDStatusPagesResponse) GetIncidentsStatusPageEntity() *components.IncidentsStatusPageEntity {
	if o == nil {
		return nil
	}
	return o.IncidentsStatusPageEntity
}
