// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type PostV1SeverityMatrixImpactsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Create a new impact
	SeverityMatrixImpactEntity *components.SeverityMatrixImpactEntity
}

func (o *PostV1SeverityMatrixImpactsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostV1SeverityMatrixImpactsResponse) GetSeverityMatrixImpactEntity() *components.SeverityMatrixImpactEntity {
	if o == nil {
		return nil
	}
	return o.SeverityMatrixImpactEntity
}
