// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type PutV1NuncConnectionsNuncConnectionIDRequestBody struct {
	CompanyName        *string `form:"name=company_name"`
	CompanyWebsite     *string `form:"name=company_website"`
	CompanyTosURL      *string `form:"name=company_tos_url"`
	GreetingTitle      *string `form:"name=greeting_title"`
	GreetingBody       *string `form:"name=greeting_body"`
	OperationalMessage *string `form:"name=operational_message"`
	Title              *string `form:"name=title"`
	// Status page condition to map your severity matrix condition to
	ConditionsNuncCondition []string `form:"name=conditions[nunc_condition]"`
	// Severity matrix condition id
	ConditionsConditionID        []string `form:"name=conditions[condition_id]"`
	ComponentsInfrastructureType []string `form:"name=components[infrastructure_type]"`
	ComponentsInfrastructureID   []string `form:"name=components[infrastructure_id]"`
	PrimaryColor                 *string  `form:"name=primary_color"`
	SecondaryColor               *string  `form:"name=secondary_color"`
	ExposedFields                []string `form:"name=exposed_fields"`
	EnableHistogram              *bool    `form:"name=enable_histogram"`
	UIVersion                    *int     `form:"name=ui_version"`
}

func (o *PutV1NuncConnectionsNuncConnectionIDRequestBody) GetCompanyName() *string {
	if o == nil {
		return nil
	}
	return o.CompanyName
}

func (o *PutV1NuncConnectionsNuncConnectionIDRequestBody) GetCompanyWebsite() *string {
	if o == nil {
		return nil
	}
	return o.CompanyWebsite
}

func (o *PutV1NuncConnectionsNuncConnectionIDRequestBody) GetCompanyTosURL() *string {
	if o == nil {
		return nil
	}
	return o.CompanyTosURL
}

func (o *PutV1NuncConnectionsNuncConnectionIDRequestBody) GetGreetingTitle() *string {
	if o == nil {
		return nil
	}
	return o.GreetingTitle
}

func (o *PutV1NuncConnectionsNuncConnectionIDRequestBody) GetGreetingBody() *string {
	if o == nil {
		return nil
	}
	return o.GreetingBody
}

func (o *PutV1NuncConnectionsNuncConnectionIDRequestBody) GetOperationalMessage() *string {
	if o == nil {
		return nil
	}
	return o.OperationalMessage
}

func (o *PutV1NuncConnectionsNuncConnectionIDRequestBody) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *PutV1NuncConnectionsNuncConnectionIDRequestBody) GetConditionsNuncCondition() []string {
	if o == nil {
		return []string{}
	}
	return o.ConditionsNuncCondition
}

func (o *PutV1NuncConnectionsNuncConnectionIDRequestBody) GetConditionsConditionID() []string {
	if o == nil {
		return []string{}
	}
	return o.ConditionsConditionID
}

func (o *PutV1NuncConnectionsNuncConnectionIDRequestBody) GetComponentsInfrastructureType() []string {
	if o == nil {
		return []string{}
	}
	return o.ComponentsInfrastructureType
}

func (o *PutV1NuncConnectionsNuncConnectionIDRequestBody) GetComponentsInfrastructureID() []string {
	if o == nil {
		return []string{}
	}
	return o.ComponentsInfrastructureID
}

func (o *PutV1NuncConnectionsNuncConnectionIDRequestBody) GetPrimaryColor() *string {
	if o == nil {
		return nil
	}
	return o.PrimaryColor
}

func (o *PutV1NuncConnectionsNuncConnectionIDRequestBody) GetSecondaryColor() *string {
	if o == nil {
		return nil
	}
	return o.SecondaryColor
}

func (o *PutV1NuncConnectionsNuncConnectionIDRequestBody) GetExposedFields() []string {
	if o == nil {
		return nil
	}
	return o.ExposedFields
}

func (o *PutV1NuncConnectionsNuncConnectionIDRequestBody) GetEnableHistogram() *bool {
	if o == nil {
		return nil
	}
	return o.EnableHistogram
}

func (o *PutV1NuncConnectionsNuncConnectionIDRequestBody) GetUIVersion() *int {
	if o == nil {
		return nil
	}
	return o.UIVersion
}

type PutV1NuncConnectionsNuncConnectionIDRequest struct {
	NuncConnectionID string                                           `pathParam:"style=simple,explode=false,name=nunc_connection_id"`
	RequestBody      *PutV1NuncConnectionsNuncConnectionIDRequestBody `request:"mediaType=application/x-www-form-urlencoded"`
}

func (o *PutV1NuncConnectionsNuncConnectionIDRequest) GetNuncConnectionID() string {
	if o == nil {
		return ""
	}
	return o.NuncConnectionID
}

func (o *PutV1NuncConnectionsNuncConnectionIDRequest) GetRequestBody() *PutV1NuncConnectionsNuncConnectionIDRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type PutV1NuncConnectionsNuncConnectionIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Update your company's information and other components in the specified FireHydrant hosted status page.
	NuncConnectionEntity *components.NuncConnectionEntity
}

func (o *PutV1NuncConnectionsNuncConnectionIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PutV1NuncConnectionsNuncConnectionIDResponse) GetNuncConnectionEntity() *components.NuncConnectionEntity {
	if o == nil {
		return nil
	}
	return o.NuncConnectionEntity
}
