// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type UpdateIncidentNoteRequest struct {
	NoteID                                string                                           `pathParam:"style=simple,explode=false,name=note_id"`
	IncidentID                            string                                           `pathParam:"style=simple,explode=false,name=incident_id"`
	PatchV1IncidentsIncidentIDNotesNoteID components.PatchV1IncidentsIncidentIDNotesNoteID `request:"mediaType=application/json"`
}

func (o *UpdateIncidentNoteRequest) GetNoteID() string {
	if o == nil {
		return ""
	}
	return o.NoteID
}

func (o *UpdateIncidentNoteRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

func (o *UpdateIncidentNoteRequest) GetPatchV1IncidentsIncidentIDNotesNoteID() components.PatchV1IncidentsIncidentIDNotesNoteID {
	if o == nil {
		return components.PatchV1IncidentsIncidentIDNotesNoteID{}
	}
	return o.PatchV1IncidentsIncidentIDNotesNoteID
}

type UpdateIncidentNoteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Updates the body of a note
	EventNoteEntity *components.EventNoteEntity
}

func (o *UpdateIncidentNoteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateIncidentNoteResponse) GetEventNoteEntity() *components.EventNoteEntity {
	if o == nil {
		return nil
	}
	return o.EventNoteEntity
}
