// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type UpdateSeverityMatrixImpactRequest struct {
	ImpactID                             string                                          `pathParam:"style=simple,explode=false,name=impact_id"`
	PatchV1SeverityMatrixImpactsImpactID components.PatchV1SeverityMatrixImpactsImpactID `request:"mediaType=application/json"`
}

func (o *UpdateSeverityMatrixImpactRequest) GetImpactID() string {
	if o == nil {
		return ""
	}
	return o.ImpactID
}

func (o *UpdateSeverityMatrixImpactRequest) GetPatchV1SeverityMatrixImpactsImpactID() components.PatchV1SeverityMatrixImpactsImpactID {
	if o == nil {
		return components.PatchV1SeverityMatrixImpactsImpactID{}
	}
	return o.PatchV1SeverityMatrixImpactsImpactID
}

type UpdateSeverityMatrixImpactResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Update a specific impact
	SeverityMatrixImpactEntity *components.SeverityMatrixImpactEntity
}

func (o *UpdateSeverityMatrixImpactResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateSeverityMatrixImpactResponse) GetSeverityMatrixImpactEntity() *components.SeverityMatrixImpactEntity {
	if o == nil {
		return nil
	}
	return o.SeverityMatrixImpactEntity
}
