// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type UpdateChangeRequest struct {
	ChangeID               string                            `pathParam:"style=simple,explode=false,name=change_id"`
	PatchV1ChangesChangeID components.PatchV1ChangesChangeID `request:"mediaType=application/json"`
}

func (o *UpdateChangeRequest) GetChangeID() string {
	if o == nil {
		return ""
	}
	return o.ChangeID
}

func (o *UpdateChangeRequest) GetPatchV1ChangesChangeID() components.PatchV1ChangesChangeID {
	if o == nil {
		return components.PatchV1ChangesChangeID{}
	}
	return o.PatchV1ChangesChangeID
}

type UpdateChangeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Update a change entry
	ChangeEntity *components.ChangeEntity
}

func (o *UpdateChangeResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateChangeResponse) GetChangeEntity() *components.ChangeEntity {
	if o == nil {
		return nil
	}
	return o.ChangeEntity
}
