// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"firehydrant/internal/utils"
	"time"
)

// AlertsSirenEventEntityData - The event's payload
type AlertsSirenEventEntityData struct {
}

type AlertsSirenEventEntity struct {
	ID   *string `json:"id,omitempty"`
	Type *string `json:"type,omitempty"`
	// The event's payload
	Data      *AlertsSirenEventEntityData `json:"data,omitempty"`
	CreatedAt *time.Time                  `json:"created_at,omitempty"`
}

func (a AlertsSirenEventEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AlertsSirenEventEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AlertsSirenEventEntity) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AlertsSirenEventEntity) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *AlertsSirenEventEntity) GetData() *AlertsSirenEventEntityData {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *AlertsSirenEventEntity) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}
