// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AttachmentsLinkEntity - Attachments_LinkEntity model
type AttachmentsLinkEntity struct {
	ID          *string `json:"id,omitempty"`
	Type        *string `json:"type,omitempty"`
	DisplayText *string `json:"display_text,omitempty"`
	HrefURL     *string `json:"href_url,omitempty"`
	IconURL     *string `json:"icon_url,omitempty"`
	// Link can be edited
	Editable *bool `json:"editable,omitempty"`
	// Link can be deleted
	Deletable *bool `json:"deletable,omitempty"`
}

func (o *AttachmentsLinkEntity) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AttachmentsLinkEntity) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *AttachmentsLinkEntity) GetDisplayText() *string {
	if o == nil {
		return nil
	}
	return o.DisplayText
}

func (o *AttachmentsLinkEntity) GetHrefURL() *string {
	if o == nil {
		return nil
	}
	return o.HrefURL
}

func (o *AttachmentsLinkEntity) GetIconURL() *string {
	if o == nil {
		return nil
	}
	return o.IconURL
}

func (o *AttachmentsLinkEntity) GetEditable() *bool {
	if o == nil {
		return nil
	}
	return o.Editable
}

func (o *AttachmentsLinkEntity) GetDeletable() *bool {
	if o == nil {
		return nil
	}
	return o.Deletable
}
