// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type IntegrationsMicrosoftTeamsV2ChannelEntity struct {
	ID          *string `json:"id,omitempty"`
	ChannelID   *string `json:"channel_id,omitempty"`
	ChannelName *string `json:"channel_name,omitempty"`
	MsTeamID    *string `json:"ms_team_id,omitempty"`
	TeamName    *string `json:"team_name,omitempty"`
	ChannelURL  *string `json:"channel_url,omitempty"`
	Status      *string `json:"status,omitempty"`
	// IncidentEntity model
	Incident *IncidentEntity `json:"incident,omitempty"`
}

func (o *IntegrationsMicrosoftTeamsV2ChannelEntity) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *IntegrationsMicrosoftTeamsV2ChannelEntity) GetChannelID() *string {
	if o == nil {
		return nil
	}
	return o.ChannelID
}

func (o *IntegrationsMicrosoftTeamsV2ChannelEntity) GetChannelName() *string {
	if o == nil {
		return nil
	}
	return o.ChannelName
}

func (o *IntegrationsMicrosoftTeamsV2ChannelEntity) GetMsTeamID() *string {
	if o == nil {
		return nil
	}
	return o.MsTeamID
}

func (o *IntegrationsMicrosoftTeamsV2ChannelEntity) GetTeamName() *string {
	if o == nil {
		return nil
	}
	return o.TeamName
}

func (o *IntegrationsMicrosoftTeamsV2ChannelEntity) GetChannelURL() *string {
	if o == nil {
		return nil
	}
	return o.ChannelURL
}

func (o *IntegrationsMicrosoftTeamsV2ChannelEntity) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *IntegrationsMicrosoftTeamsV2ChannelEntity) GetIncident() *IncidentEntity {
	if o == nil {
		return nil
	}
	return o.Incident
}
