// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// VersionsUrls - An object with keys that can have different versions of an image
type VersionsUrls struct {
}

type MediaImageEntity struct {
	OriginalURL *string `json:"original_url,omitempty"`
	// An object with keys that can have different versions of an image
	VersionsUrls *VersionsUrls `json:"versions_urls,omitempty"`
}

func (o *MediaImageEntity) GetOriginalURL() *string {
	if o == nil {
		return nil
	}
	return o.OriginalURL
}

func (o *MediaImageEntity) GetVersionsUrls() *VersionsUrls {
	if o == nil {
		return nil
	}
	return o.VersionsUrls
}
