// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"openapi/types"
	"time"
)

type MetricsTicketFunnelMetricsEntityDataBucketFilterParamsEntity struct {
	// The start datetime for the period
	StartDate *time.Time `json:"start_date,omitempty"`
	// The end datetime for the period not inclusive
	EndDate *types.Date `json:"end_date,omitempty"`
}

func (m MetricsTicketFunnelMetricsEntityDataBucketFilterParamsEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MetricsTicketFunnelMetricsEntityDataBucketFilterParamsEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *MetricsTicketFunnelMetricsEntityDataBucketFilterParamsEntity) GetStartDate() *time.Time {
	if o == nil {
		return nil
	}
	return o.StartDate
}

func (o *MetricsTicketFunnelMetricsEntityDataBucketFilterParamsEntity) GetEndDate() *types.Date {
	if o == nil {
		return nil
	}
	return o.EndDate
}
