// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PatchV1StatusUpdateTemplatesStatusUpdateTemplateID - Update a single status update template
type PatchV1StatusUpdateTemplatesStatusUpdateTemplateID struct {
	Name *string `json:"name,omitempty"`
	Body *string `json:"body,omitempty"`
}

func (o *PatchV1StatusUpdateTemplatesStatusUpdateTemplateID) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *PatchV1StatusUpdateTemplatesStatusUpdateTemplateID) GetBody() *string {
	if o == nil {
		return nil
	}
	return o.Body
}
