// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PostMortemsQuestionTypeEntity - PostMortems_QuestionTypeEntity model
type PostMortemsQuestionTypeEntity struct {
	ID               *string  `json:"id,omitempty"`
	Title            *string  `json:"title,omitempty"`
	Tooltip          *string  `json:"tooltip,omitempty"`
	Kind             *string  `json:"kind,omitempty"`
	IsRequired       *bool    `json:"is_required,omitempty"`
	AvailableOptions []string `json:"available_options,omitempty"`
}

func (o *PostMortemsQuestionTypeEntity) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PostMortemsQuestionTypeEntity) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *PostMortemsQuestionTypeEntity) GetTooltip() *string {
	if o == nil {
		return nil
	}
	return o.Tooltip
}

func (o *PostMortemsQuestionTypeEntity) GetKind() *string {
	if o == nil {
		return nil
	}
	return o.Kind
}

func (o *PostMortemsQuestionTypeEntity) GetIsRequired() *bool {
	if o == nil {
		return nil
	}
	return o.IsRequired
}

func (o *PostMortemsQuestionTypeEntity) GetAvailableOptions() []string {
	if o == nil {
		return nil
	}
	return o.AvailableOptions
}
