// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TaskListItems struct {
	// A summary of the task
	Summary string `json:"summary"`
	// A long-form description for the task if additional context is helpful
	Description *string `json:"description,omitempty"`
}

func (o *TaskListItems) GetSummary() string {
	if o == nil {
		return ""
	}
	return o.Summary
}

func (o *TaskListItems) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

// PostV1TaskLists - Creates a new task list
type PostV1TaskLists struct {
	Name          string          `json:"name"`
	Description   *string         `json:"description,omitempty"`
	TaskListItems []TaskListItems `json:"task_list_items"`
}

func (o *PostV1TaskLists) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *PostV1TaskLists) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *PostV1TaskLists) GetTaskListItems() []TaskListItems {
	if o == nil {
		return []TaskListItems{}
	}
	return o.TaskListItems
}
