// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

// RunbookEntity model
type RunbookEntity struct {
	ID                *string            `json:"id,omitempty"`
	Name              *string            `json:"name,omitempty"`
	Summary           *string            `json:"summary,omitempty"`
	Description       *string            `json:"description,omitempty"`
	Type              *string            `json:"type,omitempty"`
	RunbookTemplateID *string            `json:"runbook_template_id,omitempty"`
	CreatedAt         *time.Time         `json:"created_at,omitempty"`
	UpdatedAt         *time.Time         `json:"updated_at,omitempty"`
	CreatedBy         *AuthorEntity      `json:"created_by,omitempty"`
	UpdatedBy         *AuthorEntity      `json:"updated_by,omitempty"`
	Steps             *RunbookStepEntity `json:"steps,omitempty"`
	AttachmentRule    *RulesRuleEntity   `json:"attachment_rule,omitempty"`
	// VotesEntity model
	Votes      *VotesEntity `json:"votes,omitempty"`
	IsEditable *bool        `json:"is_editable,omitempty"`
	// TeamEntity model
	Owner *TeamEntity `json:"owner,omitempty"`
	// categories the runbook applies to
	Categories                      *string `json:"categories,omitempty"`
	AutoAttachToRestrictedIncidents *bool   `json:"auto_attach_to_restricted_incidents,omitempty"`
	Tutorial                        *bool   `json:"tutorial,omitempty"`
}

func (r RunbookEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RunbookEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *RunbookEntity) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *RunbookEntity) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *RunbookEntity) GetSummary() *string {
	if o == nil {
		return nil
	}
	return o.Summary
}

func (o *RunbookEntity) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *RunbookEntity) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *RunbookEntity) GetRunbookTemplateID() *string {
	if o == nil {
		return nil
	}
	return o.RunbookTemplateID
}

func (o *RunbookEntity) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *RunbookEntity) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *RunbookEntity) GetCreatedBy() *AuthorEntity {
	if o == nil {
		return nil
	}
	return o.CreatedBy
}

func (o *RunbookEntity) GetUpdatedBy() *AuthorEntity {
	if o == nil {
		return nil
	}
	return o.UpdatedBy
}

func (o *RunbookEntity) GetSteps() *RunbookStepEntity {
	if o == nil {
		return nil
	}
	return o.Steps
}

func (o *RunbookEntity) GetAttachmentRule() *RulesRuleEntity {
	if o == nil {
		return nil
	}
	return o.AttachmentRule
}

func (o *RunbookEntity) GetVotes() *VotesEntity {
	if o == nil {
		return nil
	}
	return o.Votes
}

func (o *RunbookEntity) GetIsEditable() *bool {
	if o == nil {
		return nil
	}
	return o.IsEditable
}

func (o *RunbookEntity) GetOwner() *TeamEntity {
	if o == nil {
		return nil
	}
	return o.Owner
}

func (o *RunbookEntity) GetCategories() *string {
	if o == nil {
		return nil
	}
	return o.Categories
}

func (o *RunbookEntity) GetAutoAttachToRestrictedIncidents() *bool {
	if o == nil {
		return nil
	}
	return o.AutoAttachToRestrictedIncidents
}

func (o *RunbookEntity) GetTutorial() *bool {
	if o == nil {
		return nil
	}
	return o.Tutorial
}
