// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RunbooksWebhookDeliveryEntity struct {
	Headers    *string `json:"headers,omitempty"`
	StatusCode *string `json:"status_code,omitempty"`
}

func (o *RunbooksWebhookDeliveryEntity) GetHeaders() *string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *RunbooksWebhookDeliveryEntity) GetStatusCode() *string {
	if o == nil {
		return nil
	}
	return o.StatusCode
}
