// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

type Prerequisites struct {
}

type DefaultLogic struct {
}

type DefaultRuleData struct {
}

type RunbooksActionsEntity struct {
	ID            *string                     `json:"id,omitempty"`
	Name          *string                     `json:"name,omitempty"`
	Slug          *string                     `json:"slug,omitempty"`
	Description   *string                     `json:"description,omitempty"`
	Config        *RunbooksActionConfigEntity `json:"config,omitempty"`
	Category      *string                     `json:"category,omitempty"`
	Prerequisites *Prerequisites              `json:"prerequisites,omitempty"`
	// Integrations_IntegrationEntity model
	Integration           *IntegrationsIntegrationEntity `json:"integration,omitempty"`
	SupportedRunbookTypes []string                       `json:"supported_runbook_types,omitempty"`
	CreatedAt             *time.Time                     `json:"created_at,omitempty"`
	UpdatedAt             *time.Time                     `json:"updated_at,omitempty"`
	Automatable           *bool                          `json:"automatable,omitempty"`
	Rerunnable            *bool                          `json:"rerunnable,omitempty"`
	Repeatable            *bool                          `json:"repeatable,omitempty"`
	DefaultLogic          *DefaultLogic                  `json:"default_logic,omitempty"`
	DefaultRuleData       *DefaultRuleData               `json:"default_rule_data,omitempty"`
}

func (r RunbooksActionsEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RunbooksActionsEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *RunbooksActionsEntity) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *RunbooksActionsEntity) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *RunbooksActionsEntity) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *RunbooksActionsEntity) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *RunbooksActionsEntity) GetConfig() *RunbooksActionConfigEntity {
	if o == nil {
		return nil
	}
	return o.Config
}

func (o *RunbooksActionsEntity) GetCategory() *string {
	if o == nil {
		return nil
	}
	return o.Category
}

func (o *RunbooksActionsEntity) GetPrerequisites() *Prerequisites {
	if o == nil {
		return nil
	}
	return o.Prerequisites
}

func (o *RunbooksActionsEntity) GetIntegration() *IntegrationsIntegrationEntity {
	if o == nil {
		return nil
	}
	return o.Integration
}

func (o *RunbooksActionsEntity) GetSupportedRunbookTypes() []string {
	if o == nil {
		return nil
	}
	return o.SupportedRunbookTypes
}

func (o *RunbooksActionsEntity) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *RunbooksActionsEntity) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *RunbooksActionsEntity) GetAutomatable() *bool {
	if o == nil {
		return nil
	}
	return o.Automatable
}

func (o *RunbooksActionsEntity) GetRerunnable() *bool {
	if o == nil {
		return nil
	}
	return o.Rerunnable
}

func (o *RunbooksActionsEntity) GetRepeatable() *bool {
	if o == nil {
		return nil
	}
	return o.Repeatable
}

func (o *RunbooksActionsEntity) GetDefaultLogic() *DefaultLogic {
	if o == nil {
		return nil
	}
	return o.DefaultLogic
}

func (o *RunbooksActionsEntity) GetDefaultRuleData() *DefaultRuleData {
	if o == nil {
		return nil
	}
	return o.DefaultRuleData
}
