// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ServiceLinkEntity model
type ServiceLinkEntity struct {
	StatusCode *int `json:"status_code,omitempty"`
	// ServiceEntity model
	Service *ServiceEntity `json:"service,omitempty"`
}

func (o *ServiceLinkEntity) GetStatusCode() *int {
	if o == nil {
		return nil
	}
	return o.StatusCode
}

func (o *ServiceLinkEntity) GetService() *ServiceEntity {
	if o == nil {
		return nil
	}
	return o.Service
}
