// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"firehydrant/internal/utils"
	"time"
)

// SeverityEntity model
type SeverityEntity struct {
	Slug         *string    `json:"slug,omitempty"`
	Description  *string    `json:"description,omitempty"`
	Type         *string    `json:"type,omitempty"`
	Position     *int       `json:"position,omitempty"`
	CreatedAt    *time.Time `json:"created_at,omitempty"`
	UpdatedAt    *time.Time `json:"updated_at,omitempty"`
	SystemRecord *bool      `json:"system_record,omitempty"`
	Color        *string    `json:"color,omitempty"`
}

func (s SeverityEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SeverityEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SeverityEntity) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *SeverityEntity) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *SeverityEntity) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *SeverityEntity) GetPosition() *int {
	if o == nil {
		return nil
	}
	return o.Position
}

func (o *SeverityEntity) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *SeverityEntity) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *SeverityEntity) GetSystemRecord() *bool {
	if o == nil {
		return nil
	}
	return o.SystemRecord
}

func (o *SeverityEntity) GetColor() *string {
	if o == nil {
		return nil
	}
	return o.Color
}
