// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/utils"
	"time"
)

// TicketingProjectsProjectListItemEntity - Ticketing_Projects_ProjectListItemEntity model
type TicketingProjectsProjectListItemEntity struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	// Ticketing_ProjectConfigEntity model
	Config *TicketingProjectConfigEntity `json:"config,omitempty"`
	// Ticketing_ProjectFieldMapEntity model
	FieldMap       *TicketingProjectFieldMapEntity `json:"field_map,omitempty"`
	UpdatedAt      *time.Time                      `json:"updated_at,omitempty"`
	ConnectionSlug *string                         `json:"connection_slug,omitempty"`
}

func (t TicketingProjectsProjectListItemEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TicketingProjectsProjectListItemEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TicketingProjectsProjectListItemEntity) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TicketingProjectsProjectListItemEntity) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TicketingProjectsProjectListItemEntity) GetConfig() *TicketingProjectConfigEntity {
	if o == nil {
		return nil
	}
	return o.Config
}

func (o *TicketingProjectsProjectListItemEntity) GetFieldMap() *TicketingProjectFieldMapEntity {
	if o == nil {
		return nil
	}
	return o.FieldMap
}

func (o *TicketingProjectsProjectListItemEntity) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *TicketingProjectsProjectListItemEntity) GetConnectionSlug() *string {
	if o == nil {
		return nil
	}
	return o.ConnectionSlug
}
